//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkAPI
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Task1 = new HashSet<Task>();
        }
    
        public int TaskId { get; set; }
        public string Name { get; set; }
        public Nullable<int> SourceId { get; set; }
        public string Description { get; set; }
        public string Report { get; set; }
        public string ManagerReview { get; set; }
        public Nullable<int> Mark { get; set; }
        public Nullable<System.DateTime> ReviewedTime { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public string Creator { get; set; }
        public Nullable<int> HandlerId { get; set; }
        public string ConfirmationImage { get; set; }
        [JsonIgnore]
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Task> Task1 { get; set; }
        [JsonIgnore]
        public virtual Task Task2 { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}
